from enum import Enum as PyEnum

class TaskTypeEnum(str, PyEnum):
    ARCHIVE = 'ARCHIVE'
    RESTORE = 'RESTORE'
    VERIFY = 'VERIFY'
    EDL_PULL = 'EDL_PULL'
    QUICK_LTO_CHECK = 'QUICK_LTO_CHECK'
    CREATE_TOC = 'CREATE_TOC'
    COPY_ALES = 'COPY_ALES'
    TAR_RESTORE_VERIFY = 'TAR_RESTORE_VERIFY'
    FULL_PATH_EDL_PULL = 'FULL_PATH_EDL_PULL'
    ALFRED_PULL = 'ALFRED_PULL'
    NETBACKUP_TAR = 'NETBACKUP_TAR'
    EDIT_BCKP = 'EDIT_BCKP'
    ARCHIVE_HBO = 'ARCHIVE_HBO'
    BRU_RESTORE = 'BRU_RESTORE'


class ProcessEnum(str, PyEnum):
    NA = 'NA'
    CHECKING_MD5 = 'CHECKING_MD5'
    CREATING_TOC_MD5 = 'CREATING TOC-MD5'  # FIX
    LOADING = 'LOADING'
    FORMATING_TAPE = 'FORMATING TAPE'  # REMOVE SPACES
    MOUNTING = 'MOUNTING'
    ARCHIVING = 'ARCHIVING'
    RESTORING = 'RESTORING'
    VERIFYING = 'VERIFYING'
    COMPARING = 'COMPARING'
    DELETING = 'DELETING'
    UNMOUNTING = 'UNMOUNTING'
    UNLOADING = 'UNLOADING'


class PullFileTypeEnum(str, PyEnum):
    NA = 'NA'
    IMAGE_SEQ = 'IMAGE_SEQ'
    FILES = 'FILES'
    FOLDERS = 'FOLDERS'
    ALL = 'ALL'


